-- ================================================================
-- PROJECT  : IPL Ball-by-Ball Analysis
-- AUTHOR   : Yashwanth
-- FILE     : schema.sql
-- DESC     : Table structure for IPL ball-by-ball data
-- ================================================================

CREATE TABLE ipl_balls (
    idx               INT,
    match_id          INT,
    date              DATE,
    match_type        VARCHAR(10),
    event_name        VARCHAR(100),
    innings           INT,
    batting_team      VARCHAR(100),
    bowling_team      VARCHAR(100),
    over              INT,
    ball              INT,
    ball_no           FLOAT,
    batter            VARCHAR(100),
    bat_pos           INT,
    runs_batter       INT,
    balls_faced       INT,
    bowler            VARCHAR(100),
    valid_ball        INT,
    runs_extras       INT,
    runs_total        INT,
    runs_bowler       INT,
    runs_not_boundary VARCHAR(10),
    extra_type        VARCHAR(50),
    non_striker       VARCHAR(100),
    non_striker_pos   INT,
    wicket_kind       VARCHAR(50),
    player_out        VARCHAR(100),
    fielders          VARCHAR(200),
    runs_target       VARCHAR(50),
    review_batter     VARCHAR(100),
    team_reviewed     VARCHAR(100),
    review_decision   VARCHAR(50),
    umpire            VARCHAR(100),
    umpires_call      VARCHAR(10),
    player_of_match   VARCHAR(100),
    match_won_by      VARCHAR(100),
    win_outcome       VARCHAR(100),
    toss_winner       VARCHAR(100),
    toss_decision     VARCHAR(20),
    venue             VARCHAR(200),
    city              VARCHAR(100),
    day               INT,
    month             INT,
    year              INT,
    season            VARCHAR(20),
    gender            VARCHAR(10),
    team_type         VARCHAR(20),
    superover_winner  VARCHAR(100),
    result_type       VARCHAR(50),
    method            VARCHAR(50),
    balls_per_over    INT,
    overs             INT,
    event_match_no    VARCHAR(50),
    stage             VARCHAR(50),
    match_number      VARCHAR(50),
    team_runs         INT,
    team_balls        INT,
    team_wicket       INT,
    new_batter        VARCHAR(100),
    power_surge_start VARCHAR(50),
    batter_runs       INT,
    batter_balls      INT,
    bowler_wicket     INT,
    batting_partners  VARCHAR(200),
    next_batter       VARCHAR(100),
    striker_out       VARCHAR(10)
);
